### ISSUE TITLE
Can't run on catservet

### ISSUE THREAD

**Issue by djkcyl** [Mezy/UhcCore#20]
Can't run on catservet,Joining the server when loading will cause the client and server to crash at the same time

server log [latest.log](https://github.com/Mezy/UhcCore/files/4383423/latest.log)
client lod [latest.log](https://github.com/Mezy/UhcCore/files/4383425/latest.log)

**Comment by djkcyl** [comment]
This is [catserver](https://mega.nz/#!nQk31ZoZ)

**Comment by Mezy** [comment]
World loading on cat server works differently, therefore the plugin is not compatible.
