### ISSUE TITLE
PreStart countdown discrepancy

### ISSUE THREAD

**Issue by varGeneric** [Mezy/UhcCore#23]
The text for the game start countdown is "Starting in %time% seconds."
https://github.com/Mezy/UhcCore/blob/2a339b901cebe137848b223422410f89ca535e3e/src/main/java/com/gmail/val59000mc/languages/Lang.java#L197
This combined with the use of formatted time in PreStartThread results in weird redundant text like "Starting in 10s seconds." (ten seconds seconds?)
https://github.com/Mezy/UhcCore/blob/2a339b901cebe137848b223422410f89ca535e3e/src/main/java/com/gmail/val59000mc/threads/PreStartThread.java#L68
This is also differs from the rest of the countdown which does not use `TimeUtils.getFormattedTime` substituted into the same string. 
https://github.com/Mezy/UhcCore/blob/2a339b901cebe137848b223422410f89ca535e3e/src/main/java/com/gmail/val59000mc/threads/PreStartThread.java#L71

This looks like unintended behaviour that could be fixed by making the first PreStart message not use `TimeUtils.getFormattedTime`.

**Comment by Mezy** [comment]
Fixed, thanks for reporting!
