### ISSUE TITLE
Custom potions in kits and flower power no longer working

### ISSUE THREAD

**Issue by NightFuryStrike** [Mezy/UhcCore#29]
Plugin Version: 1.17.2

Fails to load custom potions in kits and flower power.
Works fine in 1.17.1

Examples:

`      - '{"type":"POTION","display-name":"Mining Potion","base-effect":{"type":"WATER"},"custom-effects":[{"type":"FAST_DIGGING","duration":6000,"amplifier":2}]}'`

`  - '{"type":"POTION","display-name":"Dragon Potion","base-effect":{"type":"UNCRAFTABLE"},"custom-effects":[{"type":"SPEED","duration":1200,"amplifier":0},{"type":"HEAL","duration":1,"amplifier":0},{"type":"DAMAGE_RESISTANCE","duration":1200,"amplifier":0},{"type":"FIRE_RESISTANCE","duration":1200,"amplifier":0},{"type":"ABSORPTION","duration":1200,"amplifier":0}]}'`

![image](https://user-images.githubusercontent.com/56176412/80273048-63c80480-86a5-11ea-9655-29819cbdd662.png)
![image](https://user-images.githubusercontent.com/56176412/80273068-9245df80-86a5-11ea-802f-c03ba9967359.png)

**Comment by Mezy** [comment]
https://github.com/Mezy/UhcCore/blob/171511de94705ff6f881c4ebd8aaa4c89fbbd6be/src/main/java/com/gmail/val59000mc/utils/JsonItemUtils.java#L298

**Comment by Mezy** [comment]
Fixed on next update, thanks for reporting!
