### ISSUE TITLE
Items not given upon first join

### ISSUE THREAD

**Issue by DavyNavy3** [Mezy/UhcCore#34]
I have a UHC server on my network, using spigot 1.8.8, and when players first join the UHC server they don't receive any items in there inventory. They are forced to rejoin to obtain them.

**Comment by Mezy** [comment]
Probably due to another plugin, try removing all plugins except for UhcCore.

**Comment by DavyNavy3** [comment]
Oh yea, thanks for reminding me, it was due to PerWorldInventory plugin. That fixed the issue ;)
