### ISSUE TITLE
[UhcCore] Picking random seed from list : null

### ISSUE THREAD

**Issue by HimbeersaftLP** [Mezy/UhcCore#51]
The plugins's console output on startup claims the picked seed is null, even though the server's output clearly shows the right one in `Preparing start region for level 1 (Seed: ...)`

I assume this is because you unintentionally appended `mapName` and not `mapSeed` to the string here:
https://github.com/Mezy/UhcCore/blob/9b47a8f83e0b64e817c1b99164773a28349ba275/src/main/java/com/gmail/val59000mc/maploader/MapLoader.java#L76

**Comment by Mezy** [comment]
Fixed, thanks for reporting!
