### ISSUE TITLE
Veins not generating properly

### ISSUE THREAD

**Issue by Laurenshup** [Mezy/UhcCore#54]
After downloading the source code into IntelliJ and then building it, I have seen that the veins are not being loaded correctly. When setting diamond ores to generate a lot, I can only see it working in the spawn chunk, in others it is default Minecraft.
However, with the download from SpigotMC it works fine this concludes to me that it should be broken after release 1.18.1.
Let me know if more information is needed.

**Comment by titivermeesch** [comment]
Just to be curious, does this also happen when you build previous versions or only with this one?

**Comment by Laurenshup** [comment]
With 1.18.1 (Tagged) it works fine.
