### ISSUE TITLE
hunger not going down

### ISSUE THREAD

**Issue by Celophy** [Mezy/UhcCore#60]
the hunger is not going down! how can i fix it?

**Comment by Celophy** [comment]
i am using the last version, without any other plugin, for an yt series

**Comment by steamsyyy** [comment]
It's not supposed to go down in the first place.

**Comment by Celophy** [comment]
i mean during the game

**Comment by steamsyyy** [comment]
Yeah, that's what I mean. I've run games with friends and hunger has never been a problem. Searching for hunger in the config.yml returns no results, either, so enabling hunger isn't a feature yet.

**Comment by itoncek4** [comment]
Duplicate of #45
