### ISSUE TITLE
Debug mode nether world bug

### ISSUE THREAD

**Issue by RgtArRr** [Mezy/UhcCore#71]
When I enter on a portal to nether it teleport to another overworld, and can't return with the same portal(I think this is the `world` folder and tp back to the `second-OW`). Yes it sound weird but it happens to me.

Version: UhcCore-1.18.9

Steps to reproduce:
Create a new world with all config default(i just have a few changes, and testing for worldborder)
Stop the server, change to `debug: true` (also I test alone, so `one-player-mode: true`)
Start de server
Start a game
Create a nether portal, and enter it

a few lines of output log when after change the setting

> 
> [07:16:31] [Server thread/INFO]: Preparing level "world"
> [07:16:32] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
> [07:16:33] [Server thread/INFO]: Loaded 0 spawn chunks for world world
> [07:16:33] [Server thread/INFO]: Preparing spawn area: 0%
> [07:16:33] [Server thread/INFO]: Preparing spawn area: 0%
> [07:16:33] [Server thread/INFO]: Preparing spawn area: 0%
> [07:16:33] [Server thread/INFO]: Time elapsed: 1225 ms
> [07:16:33] [Server thread/INFO]: Preparing start region for dimension minecraft:the_nether
> [07:16:33] [Server thread/INFO]: Loaded 0 spawn chunks for world world_nether
> [07:16:33] [Server thread/INFO]: Time elapsed: 538 ms
> [07:16:33] [Server thread/INFO]: [UhcCore] Enabling UhcCore v1.18.9
> [07:16:33] [Server thread/INFO]: [UhcCore] 1.16 Server detected!
> [07:16:34] [Server thread/INFO]: [UhcCore] Loading plugins/UhcCore/scoreboard.yml
> [07:16:34] [Server thread/INFO]: [UhcCore] Loading plugins/UhcCore/storage.yml
> [07:16:34] [Server thread/INFO]: [uhcinfo] Enabling uhcinfo v1.0.0
> [07:16:41] [Server thread/INFO]: [net.dv8tion.jda.api.JDA] Login Successful!
> [07:16:42] [Server thread/INFO]: Running delayed init tasks
> [07:16:42] [Server thread/INFO]: [UhcCore] Loading plugins/UhcCore/lang.yml
> [07:16:42] [JDA MainWS-ReadThread/INFO]: [net.dv8tion.jda.internal.requests.WebSocketClient] Connected to WebSocket
> [07:16:42] [Server thread/INFO]: [UhcCore] Loading plugins/UhcCore/config.yml
> [07:16:42] [Server thread/INFO]: [UhcCore] Loading plugins/UhcCore/storage.yml
> [07:16:42] [Server thread/WARN]: [UhcCore] WorldEdit plugin not found, there will be no support of schematics.
> [07:16:42] [Server thread/WARN]: [UhcCore] Vault plugin not found, there will be no support of economy rewards.
> [07:16:42] [Server thread/WARN]: [UhcCore] ProtocolLib plugin not found.
> [07:16:42] [Server thread/INFO]: [UhcCore] Loading custom craft for golden heads
> [07:16:42] [Server thread/WARN]: Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
> [07:16:43] [JDA MainWS-ReadThread/INFO]: [net.dv8tion.jda.api.JDA] Finished Loading!
> [07:17:06] [Server thread/INFO]: [UhcCore] Border start size is 200
> [07:17:06] [Server thread/INFO]: [UhcCore] Border end size is 200
> [07:17:06] [Server thread/INFO]: [UhcCore] Border moves : true
> [07:17:06] [Server thread/INFO]: [UhcCore] Border timeBeforeEnd : 300
> [07:17:06] [Server thread/INFO]: [UhcCore] Start loading kits
> [07:17:06] [Server thread/INFO]: [UhcCore] Loading plugins/UhcCore/kits.yml
> [07:17:06] [Server thread/INFO]: [UhcCore] Loaded 0 kits
> [07:17:06] [Server thread/INFO]: [UhcCore] Loading banned crafts list
> [07:17:06] [Server thread/INFO]: [UhcCore] Loading plugins/UhcCore/crafts.yml
> [07:17:06] [Server thread/INFO]: [UhcCore] Removed recipe for minecraft:suspicious_stew
> [07:17:06] [Server thread/INFO]: [UhcCore] Loading custom crafts
> [07:17:06] [Server thread/INFO]: [UhcCore] Loading plugins/UhcCore/crafts.yml
> [07:17:06] [Server thread/INFO]: [UhcCore] Done loading custom crafts
> [07:17:06] [Server thread/INFO]: Preparing start region for dimension minecraft:59d58a96-3298-46e4-9a1c-372f0ca1fde3
> [07:17:07] [Server thread/INFO]: Loaded 0 spawn chunks for world 59d58a96-3298-46e4-9a1c-372f0ca1fde3
> [07:17:09] [Server thread/INFO]: Preparing spawn area: 0%
> [07:17:09] [Server thread/INFO]: Preparing spawn area: 0%
> [07:17:09] [Server thread/INFO]: Preparing spawn area: 0%
> [07:17:09] [Server thread/INFO]: Preparing spawn area: 0%
> [07:17:09] [Server thread/INFO]: Preparing spawn area: 0%
> [07:17:09] [Server thread/INFO]: Preparing spawn area: 0%
> [07:17:09] [Server thread/INFO]: Preparing spawn area: 0%
> [07:17:10] [Server thread/INFO]: Preparing spawn area: 0%
> [07:17:10] [Server thread/INFO]: Time elapsed: 3635 ms
> [07:17:16] [Server thread/INFO]: Preparing start region for dimension minecraft:2f44ba17-f340-4e6d-bd48-563d73450ce0
> [07:17:17] [Server thread/INFO]: Loaded 0 spawn chunks for world 2f44ba17-f340-4e6d-bd48-563d73450ce0
> [07:17:18] [Server thread/INFO]: Time elapsed: 2040 ms
> [07:17:18] [Server thread/WARN]: A manual (plugin-induced) save has been detected while server is configured to auto-save. This may affect performance.
> [07:17:36] [Server thread/INFO]: [UhcCore] No WorldEdit installed so ending with deathmatch at 0 0
> [07:17:36] [Server thread/INFO]: [UHC] Players are now allowed to join
> [07:17:36] [Server thread/INFO]: Done (68.546s)! For help, type "help"
> 
>

**Comment by Mezy** [comment]
This happens with debugging disabled as well?

**Comment by RgtArRr** [comment]
Yep, because it delete worlds and pregenerate another.
