### ISSUE TITLE
Install schematic

### ISSUE THREAD

**Issue by JuqnDev** [Mezy/UhcCore#73]
How could I install the schematic to the world edit to clean the 0,0

**Comment by BelKed** [comment]
If I understand correct, you want to add schematic to UhcCore plugin. Here are steps, you have to do:

1. First, select object with _WorldEdit wand_ (command to give it – `//wand`, default _Wooden Axe_).
2. Then stand on place, which you want (in UhcCore it will be `0,0`).
3. Use the `//copy` command.
4. Save it to the file with the `/schem save <filename>` command. Filename should be `lobby` for lobby schematic, `nether` for underground nether schematic or `arena` for deadmatch arena schematic.
5. Get your schematic file:
    - If you done that on server, your schematic is now exported in server folder – `<path_to_server_folder>/plugins/WorldEdit/schematics/<filename>.schem` or something similar.
    - If you done that on singleplayer world, your schematic is now exported in Minecraft folder – `<path_to_minecraft_folder/config/worldedit/schematics/<filename>.schem` or something similar.
6. Grab the schematic file (`<filename>.schem`) that you created from the folder.
7. Put that file to `<path_to_server_folder>/plugins/UhcCore/<filename>.schem`.
8. Now you can start or restart your Minecraft server on which you have UhcCore and WorldEdit and you should see schematic loaded...

If you have any questions, please feel free to ask.
