### ISSUE TITLE
Server gets stuck on `Loading ...`

### ISSUE THREAD

**Issue by wafflecoffee** [Mezy/UhcCore#86]
Server is stuck having `Loading ...` in MOTD and unable to connect, no matter how long I leave it running.
Using git-Paper-599. No other plugins or anything, clean install; tried both Java 11 and Java 15 (OpenJDK). 
[latest.log](https://paste.md-5.net/lugiwumoti)
`System Info: Java 15 (OpenJDK 64-Bit Server VM 15.0.2+7) Host: Linux 5.11.4-rt11-1-rt (amd64)`
How would I fix this?

**Comment by BelKed** [comment]
Server is pregenerating world for game. Here are some tips for speed up loading: https://github.com/Mezy/UhcCore/wiki/Initial-Setup#ways-to-improve-server-performance

**Comment by wafflecoffee** [comment]
Still throws a `[23:17:02] [Server thread/WARN]: [UhcCore] Task #46 for UhcCore v1.19.2 generated an exception`.  
https://paste.md-5.net/uvenekogax

**Comment by MadeByIToncek** [comment]
This is related to java 11, updated in newest version.
